In [2]:
!pip install \
evaluate \
bert-score \
#bleurt \
sacrebleu \
huggingface_hub \
camel_tools \
textstat \
nltk

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting bert-score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: datasets>=2.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from evaluate) (4.8.5)
Requirement already satisfied: numpy>=1.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from evaluate) (2.1.4)
Requirement already satisfied: requests>=2.19.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from evaluate) (2.32.5)
Requirement already satisfied: tqdm>=4.62.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from evaluate) (3.7.0)
Requirement already satisfied: multiprocess in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from evaluate) (0.70.19)
Requirement already satisfied: fsspec>=2021.05.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from fsspec[http]>=2021.05.0->evaluate) (2026.2.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from evaluate) (0.17.3)
Requirement already satisfied: packaging in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from evaluate) (25.0)
Requirement already satisfied: torch>=1.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from bert-score) (2.8.0+cu128)
Requirement already satisfied: transformers>=3.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from bert-score) (4.35.0)
Requirement already satisfied: matplotlib in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from bert-score) (3.8.2)
Requirement already satisfied: filelock in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets>=2.0.0->evaluate) (24.0.0)
Requirement already satisfied: httpx<1.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Collecting huggingface-hub>=0.7.0 (from evaluate)
  Using cached huggingface_hub-1.13.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: pyyaml>=5.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: anyio in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.12.1)
Requirement already satisfied: certifi in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: idna in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (3.11)
Requirement already satisfied: h11>=0.16 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: typer in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from huggingface-hub>=0.7.0->evaluate) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pandas->evaluate) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: six>=1.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests>=2.19.0->evaluate) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: setuptools in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (1.14.0)
Requirement already satisfied: networkx in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (3.6.1)
Requirement already satisfied: jinja2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=1.0.0->bert-score) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=1.0.0->bert-score) (1.3.0)
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: regex!=2019.12.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers>=3.0.0->bert-score) (2026.4.4)
Requirement already satisfied: tokenizers<0.15,>=0.14 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers>=3.0.0->bert-score) (0.14.1)
Requirement already satisfied: safetensors>=0.3.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers>=3.0.0->bert-score) (0.7.0)
INFO: pip is looking at multiple versions of tokenizers to determine which version is compatible with other requirements. This could take a while.
Collecting tokenizers<0.15,>=0.14 (from transformers>=3.0.0->bert-score)
  Downloading tokenizers-0.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting transformers>=3.0.0 (from bert-score)
  Using cached transformers-5.7.0-py3-none-any.whl.metadata (33 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers>=3.0.0->bert-score)
  Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib->bert-score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib->bert-score) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib->bert-score) (1.5.0)
Requirement already satisfied: pillow>=8 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib->bert-score) (12.1.1)
Requirement already satisfied: pyparsing>=2.3.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from matplotlib->bert-score) (3.3.2)
Requirement already satisfied: click>=8.2.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from rich>=13.8.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from rich>=13.8.0->typer->huggingface-hub>=0.7.0->evaluate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
Using cached huggingface_hub-1.13.0-py3-none-any.whl (660 kB)
Using cached transformers-5.7.0-py3-none-any.whl (10.5 MB)
Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Installing collected packages: huggingface-hub, tokenizers, transformers, evaluate, bert-score
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.17.3
    Uninstalling huggingface-hub-0.17.3:
      Successfully uninstalled huggingface-hub-0.17.3
  Attempting uninstall: tokenizers━━━━━━━━━━━━━━ 0/5 [huggingface-hub]
    Found existing installation: tokenizers 0.14.1[32m0/5 [huggingface-hub]
    Uninstalling tokenizers-0.14.1:━━━━━━━━━ 0/5 [huggingface-hub]
      Successfully uninstalled tokenizers-0.14.1 0/5 [huggingface-hub]
  Attempting uninstall: transformers━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/5 [tokenizers]
    Found existing installation: transformers 4.35.0━━━━━━━━━━ 1/5 [tokenizers]
    Uninstalling transformers-4.35.0:━━━━━━━━━━━━━━━━━━━━━━━━━ 1/5 [tokenizers]
      Successfully uninstalled transformers-4.35.0━━━━━━━━━━━━ 1/5 [tokenizers]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [bert-score]5 [transformers]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
camel-tools 1.5.7 requires transformers<4.44.0,>=4.0, but you have transformers 5.7.0 which is incompatible.
Successfully installed bert-score-0.3.13 evaluate-0.4.6 huggingface-hub-1.13.0 tokenizers-0.22.2 transformers-5.7.0

In [1]:
!pip install camel_tools

Collecting camel_tools
  Downloading camel_tools-1.5.7-py3-none-any.whl.metadata (10 kB)
Collecting future (from camel_tools)
  Downloading future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: six in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from camel_tools) (1.17.0)
Collecting docopt (from camel_tools)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cachetools<=6.0.0 (from camel_tools)
  Downloading cachetools-6.0.0-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy<2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from camel_tools) (1.26.4)
Requirement already satisfied: scipy in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from camel_tools) (1.11.4)
Requirement already satisfied: pandas in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from camel_tools) (2.1.4)
Requirement already satisfied: scikit-learn in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from camel_tools) (1.3.2)
Requirement already satisfied: dill in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from camel_tools) (0.4.1)
Requirement already satisfied: torch>=2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from camel_tools) (2.8.0+cu128)
Requirement already satisfied: transformers<4.44.0,>=4.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from camel_tools) (4.35.0)
Collecting editdistance (from camel_tools)
  Downloading editdistance-0.8.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Requirement already satisfied: requests in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from camel_tools) (2.32.5)
Collecting emoji (from camel_tools)
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Collecting pyrsistent (from camel_tools)
  Downloading pyrsistent-0.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Collecting tabulate (from camel_tools)
  Downloading tabulate-0.10.0-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: tqdm in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from camel_tools) (4.67.3)
Collecting muddler (from camel_tools)
  Downloading muddler-0.1.3-py3-none-any.whl.metadata (7.5 kB)
Collecting camel-kenlm<=2025.09.16 (from camel_tools)
  Downloading camel_kenlm-2025.9.16-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (251 bytes)
Requirement already satisfied: filelock in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<4.44.0,>=4.0->camel_tools) (3.25.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<4.44.0,>=4.0->camel_tools) (0.17.3)
Requirement already satisfied: packaging>=20.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<4.44.0,>=4.0->camel_tools) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<4.44.0,>=4.0->camel_tools) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<4.44.0,>=4.0->camel_tools) (2026.4.4)
Requirement already satisfied: tokenizers<0.15,>=0.14 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<4.44.0,>=4.0->camel_tools) (0.14.1)
Requirement already satisfied: safetensors>=0.3.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers<4.44.0,>=4.0->camel_tools) (0.7.0)
Requirement already satisfied: fsspec in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.16.4->transformers<4.44.0,>=4.0->camel_tools) (2026.2.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.16.4->transformers<4.44.0,>=4.0->camel_tools) (4.15.0)
Requirement already satisfied: setuptools in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (1.14.0)
Requirement already satisfied: networkx in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (3.6.1)
Requirement already satisfied: jinja2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch>=2.0->camel_tools) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0->camel_tools) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from jinja2->torch>=2.0->camel_tools) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pandas->camel_tools) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pandas->camel_tools) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pandas->camel_tools) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->camel_tools) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->camel_tools) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->camel_tools) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->camel_tools) (2026.2.25)
Requirement already satisfied: joblib>=1.1.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from scikit-learn->camel_tools) (1.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from scikit-learn->camel_tools) (3.6.0)
Downloading camel_tools-1.5.7-py3-none-any.whl (124 kB)
Downloading cachetools-6.0.0-py3-none-any.whl (10 kB)
Downloading camel_kenlm-2025.9.16-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 4.1 MB/s  0:00:00m eta 0:00:01
Downloading editdistance-0.8.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (418 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 59.5 MB/s  0:00:00
Downloading future-1.0.0-py3-none-any.whl (491 kB)
Downloading muddler-0.1.3-py3-none-any.whl (16 kB)
Downloading pyrsistent-0.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (122 kB)
Downloading tabulate-0.10.0-py3-none-any.whl (39 kB)
Building wheels for collected packages: docopt
  Building wheel for docopt (pyproject.toml) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13782 sha256=35350358661bb1220e6a764e6f3788269aacd7aa9eb9c7c0573d966302184b5d
  Stored in directory: /teamspace/studios/this_studio/.cache/pip/wheels/1a/bf/a1/4cee4f7678c68c5875ca89eaccf460593539805c3906722228
Successfully built docopt
Installing collected packages: docopt, camel-kenlm, tabulate, pyrsistent, muddler, future, emoji, editdistance, cachetools, camel_tools
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [camel_tools] [future]
Successfully installed cachetools-6.0.0 camel-kenlm-2025.9.16 camel_tools-1.5.7 docopt-0.6.2 editdistance-0.8.1 emoji-2.15.0 future-1.0.0 muddler-0.1.3 pyrsistent-0.20.0 tabulate-0.10.0

In [3]:
import os
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import camel_tools 
from camel_tools.utils.normalize import normalize_unicode
#to normalize 'alef' variants
from camel_tools.utils.normalize import normalize_alef_maksura_ar
#to normalize 'ya2' variants
from camel_tools.utils.normalize import normalize_alef_ar
#to normalize 'teh marbota' variants
from camel_tools.utils.normalize import normalize_teh_marbuta_ar
#to remove diacritical marks
from camel_tools.utils.dediac import dediac_ar
#import textstat
import time
import os
from huggingface_hub import HfApi, hf_hub_download

In [56]:
df = pd.read_csv("gemma-3n-E4B_Curr_Egy_outputs_fixed.csv")

In [57]:
df.head()

,lecture,image_name,output
0,CHI-91486,CHI-91486-0010000.jpg,عايز اشرحلك الشريحه دي؟ الشريحه دي عنوانها Cro...
1,CHI-91486,CHI-91486-0047450.jpg,عايزين نتكلم عن الخلفيه اللي احنا بنحاول نفهمه...
2,CHI-91486,CHI-91486-0077450.jpg,عايز اشرحلك الشريحه دي اللي بتتكلم عن التكيف ا...
3,CHI-91486,CHI-91486-0111450.jpg,عايز اشرحلك الشريحه دي اللي بتتكلم عن ال Crowd...
4,CHI-91486,CHI-91486-0123450.jpg,عايز اشرحلك الصوره دي اللي فيها شرح لعمليه الت...

In [58]:
#cleaning before evaluation 
def clean(df , col):
    '''
    The input should be the df itself + the column name that contains the text data.
    '''
    #df = df.drop_duplicates(subset=[col])
    #df = df.dropna(subset=[col])

    
    df = df.reset_index(drop=True)
    df[col] = df[col].fillna("").astype(str)
    for i in range(len(df)):
        sentence = df.loc[i, col]
        sentence = normalize_unicode(sentence)
        sentence = dediac_ar(sentence)
        sentence = normalize_alef_maksura_ar(sentence)
        sentence = normalize_alef_ar(sentence)
        sentence = normalize_teh_marbuta_ar(sentence)
        #instead of removing english we keep it so its penalized for english usage
        #this regex will remove all non-Arabic letters and non-space characters
        #sentence = re.sub(r'[^\u0600-\u06FF\s]', '', sentence, flags=re.UNICODE)
        df.loc[i , col] = sentence
    return df

In [59]:
df.columns

Index(['lecture', 'image_name', 'output'], dtype='object')

In [60]:
df = clean(df , 'output')

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   lecture     1067 non-null   object
 1   image_name  1067 non-null   object
 2   output      1067 non-null   object
dtypes: object(3)
memory usage: 25.1+ KB

In [62]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1114 entries, 0 to 1113
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   lecture  1114 non-null   object
 1   image    1114 non-null   object
 2   source   1114 non-null   object
 3   aya      1114 non-null   object
 4   qwen     1114 non-null   object
 5   ain      1114 non-null   object
 6   gemma    1114 non-null   object
dtypes: object(7)
memory usage: 61.1+ KB

In [63]:
df = df.rename(columns = {'image_name' : 'image'})

In [64]:
df = df.merge(b[['image', 'source']], on='image', how='left')

In [65]:
df

,lecture,image,output,source
0,CHI-91486,CHI-91486-0010000.jpg,عايز اشرحلك الشريحه دي؟ الشريحه دي عنوانها Cro...,أهلاً، وشكراً لاهتمامكم بورقتنا البحثية عن الا...
1,CHI-91486,CHI-91486-0047450.jpg,عايزين نتكلم عن الخلفيه اللي احنا بنحاول نفهمه...,محتوى النصوص في الواقع المعزز (AR). الواقع الم...
2,CHI-91486,CHI-91486-0077450.jpg,عايز اشرحلك الشريحه دي اللي بتتكلم عن التكيف ا...,السياق المادي. وعشان نخلي بحثنا ملموس، ركزنا ع...
3,CHI-91486,CHI-91486-0111450.jpg,عايز اشرحلك الشريحه دي اللي بتتكلم عن ال Crowd...,دراستهم القايمة على المعمل. وعشان نسرع وضع إرش...
4,CHI-91486,CHI-91486-0123450.jpg,عايز اشرحلك الصوره دي اللي فيها شرح لعمليه الت...,الهدف هو جمع ملاحظات المستخدمين على مجموعة متن...
...,...,...,...,...
1062,CHI-214E5,CHI-214E5-0215000.jpg,عايزين نتكلم عن الكي لوينج كومبيتينسيز اللي هي...,اختبرنا الطلاب باستخدام اختبارات قبلية وبعدية،...
1063,CHI-214E5,CHI-214E5-0231450.jpg,عايزين نشوف ايه الفرق بين Zoom و RobotAR في تق...,أكملوا خاصتهم. وبالمثل، باستخدام الواقع المعزز...
1064,CHI-214E5,CHI-214E5-0244450.jpg,عن التعليقات اللي في الردود في الردود في الردو...,فدي كانت أبرز النقط من دراسات المستخدمين دي. م...
1065,CHI-214E5,CHI-214E5-0260450.jpg,الاساتذه كان عندهم وصول احسن ل مكان الطلاب و م...,المدربين كمان بلغوا إنهم بقوا قادرين يقدموا تو...
1066,CHI-214E5,CHI-214E5-0293000.jpg,الاسليد دي هي الخلاصه بتاعته و فيها النقاط الا...,عشان نقفل المشروع ده، عايز أسيب النقط الأساسية...

In [20]:
b = pd.read_csv('baseline_outputs.csv')
b.head()

,lecture,image,source,aya,qwen,ain,gemma
0,CHI-01C34,CHI-01C34-0339000.jpg,الأساس المنطقي للحدود دي. وبالنيابة عن زملائي ...,عندما وقت الشاشة ليس وقت الشاشة\n\nتوترات واحت...,"هذا الشرائح يتكلم عن موضوع: ""عندما يكون وقت ال...",أهلاً بكم في هذه الشريحة عن وقت الشاشة. إنها ع...,أهلاً بك يا بني! هذه الشريحة من عرض تقديمي. خل...
1,CHI-01C34,CHI-01C34-0169000.jpg,أثناء استخدام التطبيق. برز موضوعين شاملين في ن...,هذه الشريحة تعرض نتائج دراسة حول استخدام تطبيق...,هذا الشرائح بيقول:\n\n**نتائج الدراسة**\n\n(1)...,مرحباً يا طلاب! دعنا نتحدث عن هذه الشريحة.\n\n...,أهلاً بك يا بني! هذه الشريحة من عرض نتائج دراس...
2,CHI-01C34,CHI-01C34-0020000.jpg,أهلاً، اسمي صبا قواس وأنا طالبة دكتوراه في جام...,عندما وقت الشاشة ليس وقت الشاشة: التوترات والا...,"هذا الشرائح بعنوان: ""عندما يكون وقت الشاشة ليس...",أهلاً بكم، أصدقائي! دعونا نتحدث عن هذه الشريحة...,أهلاً بك يا بني! هذه شريحة من عرض تقديمي. دعني...
3,CHI-01C34,CHI-01C34-0126000.jpg,توترات. سألنا السؤال التالي: إزاي الأهالي بيخت...,هذه الشريحة تتناول أسئلة البحث المتعلقة بتطبيق...,"هذا الشرائح بعنوان ""أسئلة البحث"" وده مكتوب بخط...",مرحبا يا طلاب! دعنا نتحدث عن هذه الشريحة.\n\nا...,أهلاً بك يا بني! هذه الشريحة تتحدث عن أسئلة ال...
4,CHI-01C34,CHI-01C34-0207000.jpg,استخدام التكنولوجيا كمرحلة انتقالية. أهالي كتي...,عائلات' تجارب استخدام تطبيق تينز خلال استكشاف ...,هذا الشرائح عن تجربة العائلات في استخدام تطبيق...,مرحبا يا طلاب! دعنا نتحدث عن هذه الشريحة عن تج...,أهلاً بك يا بني/يا بنتي، سأشرح لك هذه الشريحة ...

In [44]:
import evaluate
from bert_score import score
import numpy as np
import bert_score


meteor = evaluate.load("meteor")       # METEOR
bleu = evaluate.load("bleu")           # BLEU
chrf = evaluate.load("chrf")           # CHRF
bleurt = evaluate.load("bleurt")       # BLEURT

[nltk_data] Downloading package wordnet to
[nltk_data]     /teamspace/studios/this_studio/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /teamspace/studios/this_studio/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /teamspace/studios/this_studio/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Downloading builder script: 0.00B [00:00, ?B/s]

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1777645221.739590   89326 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1777645221.949104   89326 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX512_FP16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1777645223.199351   89326 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Using default checkpoint 'bleurt-base-128' for sequence maximum length 128. You can use a bigger model for better results with e.g.: evaluate.load('bleurt', config_name='bleurt-large-512').

Downloading data:   0%|          | 0.00/405M [00:00<?, ?B/s]

INFO:tensorflow:Reading checkpoint /teamspace/studios/this_studio/.cache/huggingface/metrics/bleurt/default/downloads/extracted/c9567476201aa8527ea010c5ce7f3b534bd6d445678239cb4a0c4147530e5f31/bleurt-base-128.
INFO:tensorflow:Config file found, reading.
INFO:tensorflow:Will load checkpoint bert_custom
INFO:tensorflow:Loads full paths and checks that files exists.
INFO:tensorflow:... name:bert_custom
INFO:tensorflow:... vocab_file:vocab.txt
INFO:tensorflow:... bert_config_file:bert_config.json
INFO:tensorflow:... do_lower_case:True
INFO:tensorflow:... max_seq_length:128
INFO:tensorflow:Creating BLEURT scorer.
INFO:tensorflow:Creating WordPiece tokenizer.
INFO:tensorflow:WordPiece tokenizer instantiated.
INFO:tensorflow:Creating Eager Mode predictor.
INFO:tensorflow:Loading model.

W0000 00:00:1777645241.414816   89326 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

INFO:tensorflow:BLEURT initialized.

INFO:tensorflow:BLEURT initialized.

In [43]:
#!pip install nltk
#!pip install sacrebleu
#!pip install git+https://github.com/google-research/bleurt.git

Collecting git+https://github.com/google-research/bleurt.git
  Cloning https://github.com/google-research/bleurt.git to /tmp/pip-req-build-j2hr4q0p
  Running command git clone --filter=blob:none --quiet https://github.com/google-research/bleurt.git /tmp/pip-req-build-j2hr4q0p

  Resolved https://github.com/google-research/bleurt.git to commit cebe7e6f996b40910cfaa520a63db47807e3bf5c
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from BLEURT==0.0.2) (2.1.4)
Requirement already satisfied: numpy in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from BLEURT==0.0.2) (1.26.4)
Requirement already satisfied: scipy in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from BLEURT==0.0.2) (1.11.4)
Collecting tensorflow (from BLEURT==0.0.2)
  Downloading tensorflow-2.21.0-cp312-cp312-manylinux_2_27_x86_64.whl.metadata (4.4 kB)
Collecting tf-slim>=1.1 (from BLEURT==0.0.2)
  Downloading tf_slim-1.1.0-py2.py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: sentencepiece in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from BLEURT==0.0.2) (0.2.1)
Requirement already satisfied: absl-py>=0.2.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from tf-slim>=1.1->BLEURT==0.0.2) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pandas->BLEURT==0.0.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pandas->BLEURT==0.0.2) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pandas->BLEURT==0.0.2) (2025.3)
Requirement already satisfied: six>=1.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->BLEURT==0.0.2) (1.17.0)
Collecting astunparse>=1.6.0 (from tensorflow->BLEURT==0.0.2)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow->BLEURT==0.0.2)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow->BLEURT==0.0.2)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow->BLEURT==0.0.2)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow->BLEURT==0.0.2)
  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow->BLEURT==0.0.2)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from tensorflow->BLEURT==0.0.2) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from tensorflow->BLEURT==0.0.2) (7.34.0)
Requirement already satisfied: requests<3,>=2.21.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from tensorflow->BLEURT==0.0.2) (2.32.5)
Requirement already satisfied: setuptools in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from tensorflow->BLEURT==0.0.2) (80.10.2)
Collecting termcolor>=1.1.0 (from tensorflow->BLEURT==0.0.2)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from tensorflow->BLEURT==0.0.2) (4.15.0)
Collecting wrapt>=1.11.0 (from tensorflow->BLEURT==0.0.2)
  Downloading wrapt-2.1.2-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (7.4 kB)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from tensorflow->BLEURT==0.0.2) (1.78.0)
Collecting keras>=3.12.0 (from tensorflow->BLEURT==0.0.2)
  Downloading keras-3.14.0-py3-none-any.whl.metadata (6.3 kB)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow->BLEURT==0.0.2)
  Downloading h5py-3.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow->BLEURT==0.0.2)
  Downloading ml_dtypes-0.5.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.9 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (2026.2.25)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow->BLEURT==0.0.2) (0.46.3)
Requirement already satisfied: rich in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from keras>=3.12.0->tensorflow->BLEURT==0.0.2) (14.3.3)
Collecting namex (from keras>=3.12.0->tensorflow->BLEURT==0.0.2)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow->BLEURT==0.0.2)
  Downloading optree-0.19.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (34 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from rich->keras>=3.12.0->tensorflow->BLEURT==0.0.2) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from rich->keras>=3.12.0->tensorflow->BLEURT==0.0.2) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow->BLEURT==0.0.2) (0.1.2)
Downloading tf_slim-1.1.0-py2.py3-none-any.whl (352 kB)
Downloading tensorflow-2.21.0-cp312-cp312-manylinux_2_27_x86_64.whl (572.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.6/572.6 MB 91.4 MB/s  0:00:04m0:00:0100:01
Downloading h5py-3.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 11.9 MB/s  0:00:00 eta 0:00:01
Downloading ml_dtypes-0.5.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 265.4 MB/s  0:00:00
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading keras-3.14.0-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 139.9 MB/s  0:00:00
Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 141.6 MB/s  0:00:00
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading wrapt-2.1.2-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (121 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.19.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (451 kB)
Building wheels for collected packages: BLEURT
  Building wheel for BLEURT (pyproject.toml) ... done
  Created wheel for BLEURT: filename=bleurt-0.0.2-py3-none-any.whl size=16456845 sha256=c363de80085229999a5b3f5584c6545aca95e9890c3d0edf4abe217ab53f30fc
  Stored in directory: /tmp/pip-ephem-wheel-cache-2b0fz3kv/wheels/7d/7d/6a/b06f2c763c081f3de412125c1e0bcbc941dc14da222f7c4273
Successfully built BLEURT
Installing collected packages: namex, libclang, flatbuffers, wrapt, tf-slim, termcolor, optree, opt_einsum, ml_dtypes, h5py, google_pasta, gast, astunparse, keras, tensorflow, BLEURT
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/16 [BLEURT]15/16 [BLEURT]low]
Successfully installed BLEURT-0.0.2 astunparse-1.6.3 flatbuffers-25.12.19 gast-0.7.0 google_pasta-0.2.0 h5py-3.14.0 keras-3.14.0 libclang-18.1.1 ml_dtypes-0.5.4 namex-0.1.0 opt_einsum-3.4.0 optree-0.19.0 tensorflow-2.21.0 termcolor-3.3.0 tf-slim-1.1.0 wrapt-2.1.2

In [66]:
references = df['source'].tolist()
predictions = df["output"].tolist()

In [45]:
# computationally expenisive to an extent
from transformers import AutoTokenizer, AutoModelForSequenceClassification
model_name = "AMR-KELEG/Sentence-ALDi"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

def compute_aldi(predictions):
    sum = 0
    for p in predictions:
        inputs = tokenizer(p, return_tensors="pt")
        outputs = model(**inputs)
        logits = outputs.logits
        sum += min(max(0, logits[0][0].item()), 1)
    mean  = sum / len(predictions)
    return mean

config.json:   0%|          | 0.00/978 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/376 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/651M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/651M [00:00<?, ?B/s]

In [67]:
meteor_score = meteor.compute(predictions=predictions, references=references)
print("METEOR:", meteor_score)

bleu_score = bleu.compute(predictions=predictions, references=references)
print("BLEU:", bleu_score)

chrf_score = chrf.compute(predictions=predictions, references=references)
print("CHRF+:", chrf_score)


bleurt_score = bleurt.compute(predictions=predictions, references=references)
print("BLEURT:", np.mean(bleurt_score['scores']))

P, R, F1 = bert_score.score(predictions, references, lang="ar", verbose=True)

print("Bert score Precision:", P.mean().item())
print("Bert score Recall:", R.mean().item())
print("Bert score F1:", F1.mean().item())

METEOR: {'meteor': 0.04257492785950839}
BLEU: {'bleu': 0.002498637961256573, 'precisions': [0.05244224522631371, 0.005399984571472653, 0.0008627586315079453, 0.00015953288770480034], 'brevity_penalty': 1.0, 'length_ratio': 1.1792439321257249, 'translation_length': 65882, 'reference_length': 55868}
CHRF+: {'score': 13.168198422533294, 'char_order': 6, 'word_order': 0, 'beta': 2}
BLEURT: -0.28662288350235554

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

calculating scores...
computing bert embedding.

  0%|          | 0/34 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/17 [00:00<?, ?it/s]

done in 2.64 seconds, 404.80 sentences/sec
Bert score Precision: 0.6200234293937683
Bert score Recall: 0.6333864331245422
Bert score F1: 0.6245044469833374

In [68]:
#Readability
import textstat
scores = [textstat.osman(p) for p in predictions]
print("Readability score: " , np.mean(scores))

Readability score:  44.96419532216988

In [69]:
ALDI = compute_aldi(predictions)
print("ALDI score:" , ALDI)

ALDI score: 0.4664724903583139

In [51]:
!pip install textstat

Collecting textstat
  Downloading textstat-0.7.13-py3-none-any.whl.metadata (15 kB)
Collecting pyphen (from textstat)
  Downloading pyphen-0.17.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: nltk in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from textstat) (3.9.4)
Requirement already satisfied: setuptools in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from textstat) (80.10.2)
Requirement already satisfied: click in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from nltk->textstat) (8.3.1)
Requirement already satisfied: joblib in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from nltk->textstat) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from nltk->textstat) (2026.4.4)
Requirement already satisfied: tqdm in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from nltk->textstat) (4.67.3)
Downloading textstat-0.7.13-py3-none-any.whl (177 kB)
Downloading pyphen-0.17.2-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 16.2 MB/s  0:00:00
Installing collected packages: pyphen, textstat
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [textstat]
Successfully installed pyphen-0.17.2 textstat-0.7.13